import Head from "next/head";
import Image from "next/image";
import KeyboardBackspaceIcon from "@mui/icons-material/KeyboardBackspace";
import IconButton from "@mui/material/IconButton";
import { BsArrowLeft, BsArrowRight } from "react-icons/bs";
import ProductCard from "../../components/product/productCard";
import { useRef, useState } from "react";
import baseUrl from "../../helpers/baseUrl";
import Link from "next/link";

export default function Home({ products }) {
  const scrollRef = useRef(null);
  const [g, setG] = useState(0);
  if (!products) {
    return <h1>Loading...</h1>;
  }
  function hans(n) {
    setG(n);
  }
  const handleScrollLeft = () => {
    if (scrollRef.current) {
      scrollRef.current.scrollLeft -= 350; // adjust scroll distance as needed
    }
  };

  const handleScrollRight = () => {
    if (scrollRef.current) {
      scrollRef.current.scrollLeft += 350; // adjust scroll distance as needed
    }
  };
  let un = [];
  if (products) {
    const uq = products.map((product) => product.category);
    un = [...new Set(uq)];
    un.forEach((item, index) => {
      un[index] = { id: index + 1, category: item };
    });
  }
  return (
    <>
      <Head>
        <title>Bites - A Food Ordering App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="home">
        <section>
          <div className="home_l">
            <div className="home__title">
              <p>We Serve The Taste You Love 😋</p>
            </div>
            <div className="home__cont">
              <p>
                This is a type of resturant which typicallly servers food and
                drinks in addition to light refrishments such as baked goods or
                snacks. The term comes from the french work meaning food.
              </p>
            </div>
            <div className="home__ctas">
              <Link href="/shop">
                <div>
                  <p>Shop</p>
                </div>
              </Link>
              <Link href="#section">
                <div>
                  <p>Explore</p>
                </div>
              </Link>
            </div>
          </div>
          <div className="home_m">
            <div className="home_m_">
              <div className="home_m__">
                <Image
                  alt="Image"
                  src="/food_1.png"
                  width={600}
                  height={600}
                  className="main_img"
                  priority
                />
              </div>
            </div>
          </div>
          <div className="home_r">
            <div className="home_r_">
              <div className="home__simg">
                <Image src="/dish.png" width={60} height={60} alt="image" />
              </div>
              <div className="home__t">
                <p>Dishes</p>
              </div>
            </div>
            <div className="home_r_">
              <div className="home__simg">
                <Image src="/desert.png" width={60} height={60} alt="image" />
              </div>
              <div className="home__t">
                <p>Deserts</p>
              </div>
            </div>
            <div className="home_r_">
              <div className="home__simg">
                <Image src="/drinks.png" width={60} height={60} alt="image" />
              </div>
              <div className="home__t">
                <p>Drinks</p>
              </div>
            </div>
            <div className="home_r_">
              <div className="home__simg">
                <Image src="/food.png" width={60} height={60} alt="image" />
              </div>
              <div className="home__t">
                <p>Platter</p>
              </div>
            </div>
            <div className="home_r_">
              <div className="home__simg">
                <Image src="/snacks.png" width={60} height={60} alt="image" />
              </div>
              <div className="home__t">
                <p>Snacks</p>
              </div>
            </div>
          </div>
        </section>
        <section id="section">
          <div className="section_tit">
            <div className="section_tit_">
              <p>Popular Dishes</p>
            </div>
            <div className="section_scroll">
              <div className="section_scroll_" onClick={handleScrollLeft}>
                <IconButton>
                  <BsArrowLeft className="section_scroll__" />
                </IconButton>
              </div>
              <div className="section_scroll_" onClick={handleScrollRight}>
                <IconButton>
                  <BsArrowRight className="section_scroll__" />
                </IconButton>
              </div>
            </div>
          </div>
          <div className="section_cont" ref={scrollRef}>
            {products &&
              products
                .reverse()
                .map((product) => (
                  <ProductCard
                    key={product._id}
                    id={product._id}
                    img={"/food_1.png"}
                    rating={product.ratings}
                    name={product.name}
                    desc={product.desc}
                    price={product.prices[0]}
                    product={product}
                  />
                ))}
          </div>
        </section>
        <section>
          <div className="sec_img">
            <Image src="/che.png" alt="IMage" width={700} height={700} />
          </div>
          <div className="sec_cont">
            <div className="sec_tit">
              <p style={{ textTransform: "capitalize" }}>
                We are more than multiple service
              </p>
            </div>
            <div className="sec__cont">
              <p>
                This is a type of resturant which typicallly servers food and
                drinks in addition to light refrishments such as baked goods or
                snacks. The term comes from the french work meaning food.
              </p>
            </div>
            <div className="sec_serv">
              <div className="sec_serv_">
                <div className="sec_serv_img">
                  <Image src="/o.png" alt="Image" width={60} height={60} />
                </div>
                <p>Online Order</p>
              </div>
              <div className="sec_serv_">
                <div className="sec_serv_img">
                  <Image src="/mob.png" alt="Image" width={60} height={60} />
                </div>
                <p>Pre Reservation</p>
              </div>
              <div className="sec_serv_">
                <div className="sec_serv_img">
                  <Image src="/24.png" alt="Image" width={60} height={60} />
                </div>
                <p>24/7 Sercive</p>
              </div>
              <div className="sec_serv_">
                <div className="sec_serv_img">
                  <Image src="/org.png" alt="Image" width={60} height={60} />
                </div>
                <p>Organized Foodie Place</p>
              </div>
              <div className="sec_serv_">
                <div className="sec_serv_img">
                  <Image src="/clean.png" alt="Image" width={60} height={60} />
                </div>
                <p>Clean Kitchen</p>
              </div>
              <div className="sec_serv_">
                <div className="sec_serv_img">
                  <Image src="/hat.png" alt="Image" width={60} height={60} />
                </div>
                {/* eslint-disable-next-line react/no-unescaped-entities */}
                <p>Super Chef's</p>
              </div>
            </div>
            <div className="sec_cta">
              <p>About Us</p>
            </div>
          </div>
        </section>
        <section>
          <div className="s_tit">
            <p>Our Regular Menu Pack</p>
          </div>
          <div className="s_opt">
            {un &&
              un.slice(0, 6).map((u, index) => (
                <div
                  className={g === index + 1 ? "s_opt_active s_opt_" : "s_opt_"}
                  onClick={() => hans(index + 1)}
                  key={u.id}
                >
                  <p>{u.category}</p>
                </div>
              ))}
          </div>
          <div className="s_holder">
            {products &&
              products
                .reverse()
                .map((product) => (
                  <ProductCard
                    key={product._id}
                    id={product._id}
                    img={"/food_1.png"}
                    rating={product.ratings}
                    name={product.name}
                    desc={product.desc}
                    price={product.prices[0]}
                    category={product.category}
                    product={product}
                  />
                ))}
          </div>
        </section>
        <section>
          <div className="se_l">
            <div className="se_tit">
              <p style={{ textTransform: "capitalize" }}>
                do you have any dinner plan today? reserve your table
              </p>
            </div>
            <div className="se_cont">
              <p>
                This is a type of resturant which typicallly servers food and
                drinks in addition to light refrishments such as baked goods or
                snacks. The term comes from the french work meaning food.
              </p>
            </div>
            <div className="se_cta">
              <p>Place Reservation</p>
            </div>
          </div>
          <div className="se_r">
            <Image src="/din.png" alt="image" width={1000} height={1000} />
          </div>
        </section>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  try {
    const res = await fetch(`${baseUrl}/api/v1/products`);
    const data = await res.json();
    return {
      props: {
        products: data.products,
      },
    };
  } catch (err) {
    return {
      props: {
        products: null,
        error: err.message,
      },
    };
  }
}
